### ISSUE TITLE
[Code-Debt] Should not use style in JSX for image imports

### ISSUE THREAD

**Issue by vreddi** [MidnightJabber/foodie-ui#12]
![image](https://user-images.githubusercontent.com/6148930/40641733-7dac3d2c-62cf-11e8-9ee4-4ee024516f68.png)

Images being imported in `SCSS` are not automatically being converting to `.webp`. Using `style` is an alternate we are using right now.

**Comment by sukritchhabra** [comment]
Not an issue. Checked and using `background-image: url('../ ... ... ...')` in `scss` uses the same loader used by jsx and leads to the imported image being compressed.
